[RFC] FSR support.
Plagman/gamescope pull request #360
Opened 2021-12-28 21:15 UTC by DadSchoorse

-U or Super + U to enable FSR for layer 0, no variable sharpness or fp16 yet. 
Includes some of my prior PRs.

2022-01-01 07:23 UTC, Joshua-Ashton commented
Shouldn't it be possible to merge the second rcas step into our composite dispatch to eliminate the extra image, dispatch, barriers, etc there?

2022-01-04 10:27 UTC, DadSchoorse commented
Yes that should be possible.

2022-01-12 20:21 UTC, DadSchoorse commented
I merged rcas and the composite step now

2022-01-26 21:47 UTC, DadSchoorse commented
There's one issue left: This increases startup times so much that it times out.

2022-01-31 02:08 UTC, Joshua-Ashton commented
@DadSchoorse Can we do lazy pipeline compilation for FSR pipelines or something?

2022-01-31 16:56 UTC, DadSchoorse commented
@Joshua-Ashton We now compile pipelines on a dedicated thread, with a lazy fallback if the requested pipeline wasn't compiled yet.

2022-01-31 19:00 UTC, Joshua-Ashton requested changes

2022-01-31 19:09 UTC, Joshua-Ashton commented on src/steamcompmgr.cpp
> +				composite.useFSRLayer0 = g_fsrUpscale;
Can also remove this in vulkan_composite.

2022-01-31 23:41 UTC, merged

2022-02-01 17:13 UTC, Bluscream commented
Stop being so smart