rendervulkan: Support for NVIDIA Image Scaling
Plagman/gamescope pull request #488
Opened 2022-05-11 20:37 UTC by esullivan-nvidia

2022-05-11 20:39 UTC, emersion commented
Maybe it would make sense to use a submodule or a Meson wrap instead of vendoring the SDK? Or maybe not, it's not that large.

2022-05-11 20:51 UTC, Martinligabue commented
why is it removing fsr support?

2022-05-11 21:02 UTC, esullivan-nvidia commented
> Maybe it would make sense to use a submodule or a Meson wrap instead of vendoring the SDK? Or maybe not, it's not that large.

I wanted to avoid pulling in the NIS examples directory which would just take up extra space and be unnecessary. Does Meson have a way to exclude some directories when it pulls in a dependency?

2022-05-11 21:05 UTC, esullivan-nvidia commented
> why is it removing fsr support?

This change is not removing support for FSR. We are adding support for NIS as an upscaling option. This change will not impact any users who are currently using FSR in Gamescope.

2022-05-12 00:42 UTC, eli-schwartz commented
> I wanted to avoid pulling in the NIS examples directory which would just take up extra space and be unnecessary. Does Meson have a way to exclude some directories when it pulls in a dependency?

How would this work from the Meson side? I assume you would download https://github.com/NVIDIAGameWorks/NVIDIAImageScaling/archive/refs/tags/v1.0.2.tar.gz and then extract only the files you need... except that you have already gone and downloaded all 27 mb of that release tarball, which is exactly what you did not want. I don't think there is anything that any application can do about that.

Possible options include:
- not caring about this at all
- re-hosting a stripped tarball, which breaks the association with the upstream release
- asking upstream to publish Github Releases archives of just the SDK
- checking these files into git, but do so in `subprojects/NVIDIAImageScaling/NIS/` instead of `src/shaders/NVIDIAImageScaling/NIS/`, which has the advantage of making it obvious to casual readers that this is imported wholesale from elsewhere rather than code specific to this project, and helps people trivially check the version from the independent `project()`, consult the SBOM, etc.

I would advise at a minimum doing option 4, option 3 would be the best if it can be arranged.

2022-05-12 11:30 UTC, Joshua-Ashton approved these changes
Looks fine to me

2022-05-12 11:30 UTC, Joshua-Ashton commented
@DadSchoorse maybe you want to take a look too?

2022-05-12 11:34 UTC, Joshua-Ashton commented
(also needs rebasing, sorry :( )

2022-05-12 13:27 UTC, DadSchoorse requested changes
Generally it's fine for now, I would like to merge it soon-ish so I can integrate it in my bigger renderer rework.

2022-05-12 21:43 UTC, esullivan-nvidia commented on src/rendervulkan.cpp
> +
Fixed

2022-05-12 21:44 UTC, esullivan-nvidia commented on src/rendervulkan.cpp
> +	}
Fixed

2022-05-12 21:44 UTC, esullivan-nvidia commented on src/rendervulkan.cpp
> +		sizeof(coef_scale) + sizeof(coef_usm);
Fixed

2022-05-13 00:24 UTC, esullivan-nvidia commented on src/shaders/descriptor_set.h
> +};
I think we would want to keep this as a uniform buffer to allow Gamescope to keep sharing a single layout between all of its pipelines without adding extra space to the push constant range size.

2022-05-13 04:13 UTC, Joshua-Ashton commented on src/shaders/descriptor_set.h
> +};
Pretty sure we're using like 100 or so bytes of push constant anyway...

2022-05-13 07:05 UTC, DadSchoorse commented on src/shaders/descriptor_set.h
> +};
Yes, our pipeline layout uses the full 128 byte range.

2022-05-13 18:29 UTC, esullivan-nvidia commented on src/shaders/descriptor_set.h
> +};
My bad, I should have double checked that. I can move this over to using push constants.

2022-05-13 19:12 UTC, esullivan-nvidia commented on src/shaders/descriptor_set.h
> +};
Fixed

2022-05-18 01:41 UTC, merged